import { NextRequest, NextResponse } from 'next/server';
import type {
  ItineraryDay,
  TransportSegment,
  AccommodationSegment,
  ExcursionSegment,
  DiningSegment,
  BudgetDashboard,
} from '@travel/shared';

const pahalgamLocation = {
  name: 'Pahalgam',
  latitude: 34.0161,
  longitude: 75.3151,
  region: 'Kashmir',
  country_code: 'IN',
  connectivity: '4G' as const,
};

const srinagarLocation = {
  name: 'Srinagar',
  latitude: 34.0837,
  longitude: 74.7973,
  region: 'Kashmir',
  country_code: 'IN',
  connectivity: '4G' as const,
};

const delhiLocation = {
  name: 'New Delhi',
  latitude: 28.6139,
  longitude: 77.209,
  region: 'Delhi',
  country_code: 'IN',
  connectivity: '5G' as const,
};

const betaabValleyLocation = {
  name: 'Betaab Valley',
  latitude: 34.0481,
  longitude: 75.3732,
  region: 'Kashmir',
  country_code: 'IN',
  connectivity: '2G' as const,
};

const ITINERARY_ID = '00000000-0000-0000-0000-000000000002';

const MOCK_ITINERARY: ItineraryDay[] = [
  {
    itinerary_id: ITINERARY_ID,
    day_number: 1,
    date: '2026-04-10',
    risk_level: 'low',
    weather_summary: 'Clear skies, 18°C, light breeze',
    nearest_hospital_km: 2.1,
    segments: [
      {
        type: 'transport',
        mode: 'flight',
        origin: delhiLocation,
        destination: srinagarLocation,
        departure: '2026-04-10T06:30:00',
        arrival: '2026-04-10T08:10:00',
        cost: { amount: 8500, currency: 'INR' },
        carrier: 'IndiGo',
        flight_number: '6E-2401',
        booking_ref: 'INDBOM2401',
        reliability_score: 0.92,
        tunnel_dependent: false,
      } as TransportSegment,
      {
        type: 'transport',
        mode: 'road',
        origin: srinagarLocation,
        destination: pahalgamLocation,
        departure: '2026-04-10T10:00:00',
        arrival: '2026-04-10T12:30:00',
        cost: { amount: 2500, currency: 'INR' },
        carrier: 'Private Cab',
        reliability_score: 0.85,
        tunnel_dependent: false,
      } as TransportSegment,
      {
        type: 'accommodation',
        property_name: 'The Pahalgam Hotel',
        location: pahalgamLocation,
        check_in: '2026-04-10T14:00:00',
        check_out: '2026-04-17T11:00:00',
        nightly_rate: { amount: 6500, currency: 'INR' },
        total_cost: { amount: 45500, currency: 'INR' },
        amenities: ['Wifi', 'Mountain View', 'Room Service', 'Bonfire', 'Heater'],
        cancellation_policy: 'Free cancellation up to 48h before check-in',
        suitability_score: 0.91,
        booking_ref: 'PHG2026-88',
      } as AccommodationSegment,
      {
        type: 'dining',
        restaurant_name: 'Lidder View Restaurant',
        location: pahalgamLocation,
        time: '2026-04-10T19:30:00',
        cuisine: 'Kashmiri Wazwan',
        budget_level: 'mid',
        dietary_match: true,
      } as DiningSegment,
    ],
  },
  {
    itinerary_id: ITINERARY_ID,
    day_number: 2,
    date: '2026-04-11',
    risk_level: 'low',
    weather_summary: 'Partly cloudy, 15°C',
    nearest_hospital_km: 4.5,
    segments: [
      {
        type: 'transport',
        mode: 'road',
        origin: pahalgamLocation,
        destination: betaabValleyLocation,
        departure: '2026-04-11T08:30:00',
        arrival: '2026-04-11T09:00:00',
        cost: { amount: 400, currency: 'INR' },
        carrier: 'Local Jeep',
        reliability_score: 0.88,
        tunnel_dependent: false,
      } as TransportSegment,
      {
        type: 'excursion',
        activity_name: 'Betaab Valley Trek & Picnic',
        location: betaabValleyLocation,
        start_time: '2026-04-11T09:00:00',
        duration_minutes: 240,
        cost: { amount: 1200, currency: 'INR' },
        difficulty: 'easy',
        weather_dependent: true,
        guide_required: false,
        altitude_meters: 2393,
      } as ExcursionSegment,
      {
        type: 'excursion',
        activity_name: 'Chandanwari Snow Point Visit',
        location: { ...pahalgamLocation, name: 'Chandanwari' },
        start_time: '2026-04-11T15:00:00',
        duration_minutes: 120,
        cost: { amount: 800, currency: 'INR' },
        difficulty: 'easy',
        weather_dependent: true,
        guide_required: false,
        altitude_meters: 2895,
      } as ExcursionSegment,
      {
        type: 'dining',
        restaurant_name: 'Wangnoo Dhaba',
        location: pahalgamLocation,
        time: '2026-04-11T13:30:00',
        cuisine: 'Kashmiri / North Indian',
        budget_level: 'budget',
        dietary_match: true,
      } as DiningSegment,
    ],
  },
  {
    itinerary_id: ITINERARY_ID,
    day_number: 3,
    date: '2026-04-12',
    risk_level: 'low',
    weather_summary: 'Sunny, 14°C',
    nearest_hospital_km: 5.8,
    segments: [
      {
        type: 'transport',
        mode: 'road',
        origin: pahalgamLocation,
        destination: { ...pahalgamLocation, name: 'Baisaran' },
        departure: '2026-04-12T07:00:00',
        arrival: '2026-04-12T08:30:00',
        cost: { amount: 2200, currency: 'INR' },
        carrier: 'Pony + Trek',
        reliability_score: 0.9,
        tunnel_dependent: false,
      } as TransportSegment,
      {
        type: 'excursion',
        activity_name: 'Baisaran Meadow & Horse Riding',
        location: { ...pahalgamLocation, name: 'Baisaran' },
        start_time: '2026-04-12T08:30:00',
        duration_minutes: 300,
        cost: { amount: 2400, currency: 'INR' },
        difficulty: 'moderate',
        weather_dependent: true,
        guide_required: true,
        altitude_meters: 2440,
      } as ExcursionSegment,
      {
        type: 'dining',
        restaurant_name: 'Pahalgam Club House Restaurant',
        location: pahalgamLocation,
        time: '2026-04-12T20:00:00',
        cuisine: 'Continental / Indian',
        budget_level: 'mid',
        dietary_match: true,
      } as DiningSegment,
    ],
  },
  {
    itinerary_id: ITINERARY_ID,
    day_number: 4,
    date: '2026-04-13',
    risk_level: 'medium',
    weather_summary: 'Light snow forecast above 2800m, 8°C',
    nearest_hospital_km: 8.2,
    segments: [
      {
        type: 'transport',
        mode: 'road',
        origin: pahalgamLocation,
        destination: { ...pahalgamLocation, name: 'Gulmarg' },
        departure: '2026-04-13T06:30:00',
        arrival: '2026-04-13T10:00:00',
        cost: { amount: 3500, currency: 'INR' },
        carrier: 'Private Cab',
        reliability_score: 0.8,
        tunnel_dependent: false,
      } as TransportSegment,
      {
        type: 'excursion',
        activity_name: 'Gulmarg Gondola Phase 1 & 2',
        location: { ...pahalgamLocation, name: 'Gulmarg' },
        start_time: '2026-04-13T10:30:00',
        duration_minutes: 180,
        cost: { amount: 3200, currency: 'INR' },
        difficulty: 'moderate',
        weather_dependent: true,
        guide_required: false,
        altitude_meters: 3980,
      } as ExcursionSegment,
      {
        type: 'dining',
        restaurant_name: 'Highlands Park Restaurant',
        location: { ...pahalgamLocation, name: 'Gulmarg' },
        time: '2026-04-13T13:30:00',
        cuisine: 'Multi-cuisine',
        budget_level: 'premium',
        dietary_match: false,
      } as DiningSegment,
      {
        type: 'transport',
        mode: 'road',
        origin: { ...pahalgamLocation, name: 'Gulmarg' },
        destination: pahalgamLocation,
        departure: '2026-04-13T17:00:00',
        arrival: '2026-04-13T20:30:00',
        cost: { amount: 3500, currency: 'INR' },
        carrier: 'Private Cab',
        reliability_score: 0.8,
        tunnel_dependent: false,
      } as TransportSegment,
    ],
  },
  {
    itinerary_id: ITINERARY_ID,
    day_number: 5,
    date: '2026-04-14',
    risk_level: 'medium',
    weather_summary: 'Overcast with showers possible in the afternoon, 12°C',
    nearest_hospital_km: 6.3,
    segments: [
      {
        type: 'excursion',
        activity_name: 'Aru Valley Trek',
        location: { ...pahalgamLocation, name: 'Aru Valley' },
        start_time: '2026-04-14T08:00:00',
        duration_minutes: 210,
        cost: { amount: 1500, currency: 'INR' },
        difficulty: 'moderate',
        weather_dependent: true,
        guide_required: true,
        altitude_meters: 2414,
      } as ExcursionSegment,
      {
        type: 'excursion',
        activity_name: 'Lidder River White Water Rafting',
        location: pahalgamLocation,
        start_time: '2026-04-14T14:00:00',
        duration_minutes: 90,
        cost: { amount: 1800, currency: 'INR' },
        difficulty: 'hard',
        weather_dependent: true,
        guide_required: true,
        altitude_meters: 2130,
      } as ExcursionSegment,
      {
        type: 'dining',
        restaurant_name: "Mama's Kitchen Pahalgam",
        location: pahalgamLocation,
        time: '2026-04-14T19:00:00',
        cuisine: 'Home-style Kashmiri',
        budget_level: 'budget',
        dietary_match: true,
      } as DiningSegment,
    ],
  },
  {
    itinerary_id: ITINERARY_ID,
    day_number: 6,
    date: '2026-04-15',
    risk_level: 'low',
    weather_summary: 'Clear and sunny, 17°C',
    nearest_hospital_km: 2.1,
    segments: [
      {
        type: 'excursion',
        activity_name: 'Pahalgam Bazaar & Saffron Farm Visit',
        location: pahalgamLocation,
        start_time: '2026-04-15T10:00:00',
        duration_minutes: 180,
        cost: { amount: 500, currency: 'INR' },
        difficulty: 'easy',
        weather_dependent: false,
        guide_required: false,
        altitude_meters: 2130,
      } as ExcursionSegment,
      {
        type: 'excursion',
        activity_name: 'Sunset Photography at Lidder Viewpoint',
        location: pahalgamLocation,
        start_time: '2026-04-15T17:00:00',
        duration_minutes: 90,
        cost: { amount: 0, currency: 'INR' },
        difficulty: 'easy',
        weather_dependent: true,
        guide_required: false,
        altitude_meters: 2200,
      } as ExcursionSegment,
      {
        type: 'dining',
        restaurant_name: 'Shamyana Restaurant',
        location: pahalgamLocation,
        time: '2026-04-15T13:00:00',
        cuisine: 'Kashmiri Wazwan',
        budget_level: 'mid',
        dietary_match: true,
      } as DiningSegment,
      {
        type: 'dining',
        restaurant_name: 'Hotel Mount View Café',
        location: pahalgamLocation,
        time: '2026-04-15T20:00:00',
        cuisine: 'Indian / Continental',
        budget_level: 'mid',
        dietary_match: true,
      } as DiningSegment,
    ],
  },
  {
    itinerary_id: ITINERARY_ID,
    day_number: 7,
    date: '2026-04-16',
    risk_level: 'low',
    weather_summary: 'Clear morning, 13°C',
    nearest_hospital_km: 2.1,
    segments: [
      {
        type: 'transport',
        mode: 'road',
        origin: pahalgamLocation,
        destination: srinagarLocation,
        departure: '2026-04-16T09:00:00',
        arrival: '2026-04-16T11:30:00',
        cost: { amount: 2500, currency: 'INR' },
        carrier: 'Private Cab',
        reliability_score: 0.9,
        tunnel_dependent: false,
      } as TransportSegment,
      {
        type: 'dining',
        restaurant_name: 'Ahdoos Restaurant Srinagar',
        location: srinagarLocation,
        time: '2026-04-16T12:30:00',
        cuisine: 'Kashmiri',
        budget_level: 'mid',
        dietary_match: true,
      } as DiningSegment,
      {
        type: 'transport',
        mode: 'flight',
        origin: srinagarLocation,
        destination: delhiLocation,
        departure: '2026-04-16T17:45:00',
        arrival: '2026-04-16T19:30:00',
        cost: { amount: 7200, currency: 'INR' },
        carrier: 'Air India',
        flight_number: 'AI-824',
        booking_ref: 'SRIAI824',
        reliability_score: 0.88,
        tunnel_dependent: false,
      } as TransportSegment,
    ],
  },
];

const MOCK_BUDGET: BudgetDashboard = {
  total_budget: { amount: 150000, currency: 'INR' },
  total_spent: { amount: 92400, currency: 'INR' },
  remaining: { amount: 57600, currency: 'INR' },
  percent_used: 61.6,
  by_category: {
    transport: { amount: 22000, currency: 'INR' },
    accommodation: { amount: 45000, currency: 'INR' },
    excursions: { amount: 14400, currency: 'INR' },
    food: { amount: 8000, currency: 'INR' },
    contingency: { amount: 3000, currency: 'INR' },
  },
  alerts: ['Transport budget 80% used'],
};

export async function GET(
  _request: NextRequest,
  { params }: { params: { id: string } }
) {
  return NextResponse.json({
    id: params.id,
    destination: 'Pahalgam, Kashmir',
    dates: { start: '2026-04-10', end: '2026-04-16' },
    party_size: 2,
    purpose: 'honeymoon',
    status: 'planning',
    itinerary: MOCK_ITINERARY,
    budget: MOCK_BUDGET,
  });
}
